
# Default color scheme
DEFAULT_CORRECT_COLOR = "#66BB66"
DEFAULT_PRESENT_COLOR = "#CCBB66"
DEFAULT_MISSING_COLOR = "#999999"

# Alternate color scheme
NEW_CORRECT_COLOR = "#3366FF"
NEW_PRESENT_COLOR = "#FF9900"
NEW_MISSING_COLOR = "#808080"

# Initial color scheme (can be changed in Wordle.py)
CURRENT_CORRECT_COLOR = DEFAULT_CORRECT_COLOR
CURRENT_PRESENT_COLOR = DEFAULT_PRESENT_COLOR
CURRENT_MISSING_COLOR = DEFAULT_MISSING_COLOR